src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/LogoutController.java, src/main/java/com/be3c/sysmetic/domain/member/service/AccountService.java, src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java, src/main/java/com/be3c/sysmetic/global/config/RedisConfig.java, src/main/java/com/be3c/sysmetic/global/error/handler/GlobalExceptionHandler.java, src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java
=> feature: find-email #18

src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/ResetPasswordRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/entity/ResetPasswordLog.java, src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java, src/main/java/com/be3c/sysmetic/domain/member/service/AccountService.java, src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java, src/test/java/com/be3c/sysmetic/global/config/security/JwtTokenProviderTest.java, src/test/java/com/be3c/sysmetic/global/config/security/RedisUtilsTest.java
비밀번호 재설정
#19
- 이메일 확인 및 인증코드 발송
- 이메일 인증코드 확인
- 비밀번호 재설정
=> feature: reset-password #19

src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/LoginController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/LogoutController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/MemberManagementController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/MemberGetResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/entity/Member.java, src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java, src/main/java/com/be3c/sysmetic/domain/member/service/LogoutService.java, src/main/java/com/be3c/sysmetic/domain/member/service/LogoutServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementService.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/global/config/security/JwtAuthenticationFilter.java, src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java, src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java
=> Feature: logout #21

src/main/java/com/be3c/sysmetic/global/config/WebConfig.java
**JWT 설정 추가**
#72
응답 헤더에 JWT 토큰 헤더 추가
=> Settings: JWT Modify #72

src/main/java/com/be3c/sysmetic/domain/member/controller/LoginController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/LoginRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/service/LoginService.java, src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java, src/main/java/com/be3c/sysmetic/global/config/security/CustomUserDetails.java, src/main/java/com/be3c/sysmetic/global/config/security/JwtAuthenticationFilter.java, src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java, src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/FolderServiceTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java, src/test/java/com/be3c/sysmetic/domain/strategy/repository/TraderStrategyRepositoryTest.java, src/test/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImplTest.java, src/test/java/com/be3c/sysmetic/global/config/security/JwtTokenProviderTest.java
JwtAuthenticationFilter 로직 수정
#71
- JwtAuthenticationFilter 수정
=> update: jwt-filter #71

src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java, src/test/java/com/be3c/sysmetic/domain/strategy/service/ExcelServiceTest.java
테스트 코드 수정
#76
- ExcelServiceTest, LoginServiceTest, LoginControllerTest = birth추가
- AccountControllerTest, AccountServiceTest = LocalDate.of(2000,1,1) 로 포맷 변경
=> fix: 테스트 코드 수정 #76

src/test/java/com/be3c/sysmetic/domain/strategy/service/StrategyApprovalServiceTest.java
StrategyApprovalServiceTest 코드 에러 수정
#76
StrategyApprovalServiceTest 코드 에러 수정
=> fix: StrategyApprovalServiceTest fix #76

src/test/java/com/be3c/sysmetic/domain/member/service/FolderServiceTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceTest.java, src/test/java/com/be3c/sysmetic/domain/strategy/repository/MethodRepositoryTest.java, src/test/java/com/be3c/sysmetic/domain/strategy/service/StrategyApprovalServiceTest.java
테스트 버그 수정
#82 
- Member 생성 시 birth 추가
- StrategyApprovalServiceTest 에러 해결
=> Fix: stock folder method interest strategy test fix #82

build.gradle, src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java, src/main/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java, src/main/java/com/be3c/sysmetic/global/config/WebClientConfig.java, src/main/java/com/be3c/sysmetic/global/util/email/apiclient/EmailApiClient.java, src/main/java/com/be3c/sysmetic/global/util/email/apiclient/EmailApiClientImpl.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/AuthCodeRequest.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/EmailRequest.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/EventOccuredBy.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/InquiryRequest.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/InterestRequest.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/StibeeApiResponse.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/StibeeApiResponseDto.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/StibeeSubscriberRequestDto.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/Subscriber.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/SubscriberRequest.java, src/main/java/com/be3c/sysmetic/global/util/email/exception/EmailSendingException.java, src/main/java/com/be3c/sysmetic/global/util/email/service/EmailService.java, src/main/java/com/be3c/sysmetic/global/util/email/service/EmailServiceImpl.java, src/main/java/com/be3c/sysmetic/global/util/email/util/BooleanToYesNoSerializer.java, src/main/java/com/be3c/sysmetic/global/util/email/util/YesNoToBooleanDeserializer.java, src/test/java/com/be3c/sysmetic/global/util/email/EmailServiceTest.java
=> Feature/mailing #43

src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
**[빌드 실패된 부분 수정]**
#43 
MemberRole enum 사용하도록 변경
=> FIX:  빌드 실패 해결 #43

src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/LoginController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/LogoutController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/MemberManagementController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java
swagger setting - member version 추가
swagger setting - member version 추가
=> chore: swagger setting - member version 추가

src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java
=> chore: swagger setting - strategy version 추가

src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/ResetPasswordRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/service/AccountService.java, src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/global/util/email/apiclient/EmailApiClient.java, src/main/java/com/be3c/sysmetic/global/util/email/apiclient/EmailApiClientImpl.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/StibeeSimpleResponse.java, src/main/java/com/be3c/sysmetic/global/util/email/dto/Subscriber.java, src/main/java/com/be3c/sysmetic/global/util/email/service/EmailService.java, src/main/java/com/be3c/sysmetic/global/util/email/service/EmailServiceImpl.java, src/test/java/com/be3c/sysmetic/global/util/email/EmailServiceTest.java
**[메일링 연동 관련 수정사항 반영]**
#43
- 관심 전략 등록 알림 로직 위치 수정
- 비밀번호 찾기에서 메일링 연동 관련 로직 추가
- 스티비 API에서 객체가 아닌 리스트 형태로 주는 응답값 자동 맵핑
=> feature: 메일링 연동 관련 수정사항 반영 #43

src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockController.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockServiceImpl.java
완료
- 오류 수정
#106 bugfix
미수정 부분 변경
=> bugfix: 오류 수정

src/test/java/com/be3c/sysmetic/domain/strategy/service/KPRatioCalculateTest.java
compile error 수정
#109 
month repository 명칭 변경으로 인한 오류 수정
=> fix: kp ratio test code 수정

src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/exception/handler/StrategyExceptionHandler.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/MonthlyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyStatisticsServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImpl.java, src/test/java/com/be3c/sysmetic/domain/strategy/service/KPRatioCalculateTest.java
=> update: file 메서드 추가

src/main/java/com/be3c/sysmetic/global/util/file/service/FileServiceImpl.java
**[삭제한 클래스 정리하여 빌드 해결]**
#111
- 쓰지 않는 클래스 정리
=> fix: 삭제한 클래스 정리 #111

src/main/java/com/be3c/sysmetic/domain/member/dto/FolderGetRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/FolderPostRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/FolderPutRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/FollowDeleteRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/FollowPostRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/FollowPutRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/service/FolderServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/AdminStrategySearchGetDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/MethodPostRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/MethodPutRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StockPutRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/test/java/com/be3c/sysmetic/domain/member/service/FolderServiceTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceTest.java
dto mapping error fix
#120 
Body > dto 매핑이 제대로 되지 않는 것 명시적으로 어노테이션 적용
=> Bugfix: dto mapping error fix #120

src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImpl.java
전략 entity 수정으로 인한 에러 해결
#130 
prepersist 제거,
전략 등록시 default 값 추가
=> fix: 전략 entity 수정 반영

src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/TokenApiResponseDto.java
토큰 확인용 API 데이터 추가
#135
- TokenApiResponseDto에 변수(phoneNumber) 추가
=> update: 토큰 확인용 API 데이터 추가

src/main/java/com/be3c/sysmetic/global/exception/GlobalExceptionHandler.java, src/main/java/com/be3c/sysmetic/global/util/file/exception/FileDeleteException.java, src/main/java/com/be3c/sysmetic/global/util/file/exception/FileNotFoundException.java, src/main/java/com/be3c/sysmetic/global/util/file/exception/FileSizeExceededException.java, src/main/java/com/be3c/sysmetic/global/util/file/exception/FileUploadException.java, src/main/java/com/be3c/sysmetic/global/util/file/service/FileService.java, src/main/java/com/be3c/sysmetic/global/util/file/service/FileServiceImpl.java, src/main/java/com/be3c/sysmetic/global/util/file/service/S3Service.java
**[파일/메일 관련 예외 처리 추가]**
#111
- FileService와 S3Service에서 발생하는 예외를 커스텀 예외로 변경하여 관리
- FileUploadException, FileDeleteException 등 예외 클래스 추가 및 로깅 기능 강화
- GlobalExceptionHandler 추가하여, 각 서비스에서 발생할 수 있는 파일 및 메일 관련 예외를 일관되게 처리하도록 구성
=> Refactor: 파일/메일 예외 처리 추가 #111

src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyListByNameDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyListRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategySearchServiceImpl.java
**전략명으로 검색**
#8 
- 전략명으로 검색 기능 추가
=> feature : 전략명으로 검색 추가 #8

src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java
**ControllerDocs implements**
#38 
implements ControlelrDocs 추가...
=> fix : implement 안함 #38

src/main/resources/application.properties
서버 포트 변경
#150
서버 포트 변경했습니다 8080 -> 8085
=> fix: server port change

src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java
토큰 확인용 API 에러 해결
#148
파일 부분 예외 수정 (IllegalArgumentException > FileNotFoundException)
=> fix: 프론트 전용 토큰 API 에러 해결

src/main/resources/application.properties
=> Fix/server port change #150

src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java, src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java, src/test/java/com/be3c/sysmetic/domain/member/controller/RegisterControllerTest.java
회원가입 파일 부분 수정
#156
회원가입 컨트롤러에  consumes = MediaType.MULTIPART_FORM_DATA_VALUE 속성 추가
=> update: register-member

src/main/java/com/be3c/sysmetic/domain/member/controller/MemberInfoController.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockController.java
멤버 정보 수정 시 오류 발생
#159 
비밀번호 수정 시 로그 저장하지 않게 변경 (try ip를 받아오는 중에 오류 발생)
멤버 정보 수정을 multiprt data로 받아오도록 변경
=> Fix: member info bugfix #159

src/main/java/com/be3c/sysmetic/domain/strategy/dto/MethodGetResponseDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockServiceImpl.java
#140 
- 매매 방식 반환 시 아이콘 경로 찾기 로직 추가
- 종목 페이징 반환 아이콘 경로 찾기 로직 추가
=> refactor: 아이콘 경로 찾기 로직 추가 #140

src/main/java/com/be3c/sysmetic/domain/member/controller/MemberInfoController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockController.java
ex) #이슈번호
path variable에 붙은 validator 어노테이션 제거
consumes 추가하며, value를 빠트린 것 추가
=> Fix: compile error resolve

src/main/java/com/be3c/sysmetic/domain/strategy/repository/MethodRepository.java, src/test/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceTest.java
1. 생성자에 맞게 쿼리 초기화
2. 테스트 코드 수정
#164
#164 이슈 확인
=> fix: Hibernate/JPA exception and test code fix

src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java
병합으로 인해 제거된 전략 상태 전환 기능 재업로드
#169 
기능 추가
=> fix: 병합으로 인해 제거된 메서드 재업로드

src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyAllowController.java
#166 
Long, Integer에 붙어있던 notblank 어노테이션 제거
=> Fix: method stock api fix #166

src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/TokenApiResponseDto.java
토큰 확인용 API 데이터 추가
#167
토큰 확인용 API의 반환값에 '회원 이름' 추가
=> update: token-api 회원 이름 추가

src/main/java/com/be3c/sysmetic/domain/member/controller/LoginController.java, src/main/java/com/be3c/sysmetic/domain/member/exception/MemberExceptionMessage.java, src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java, src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java
로그인 리팩토링
#155
- Login Controller return문 수정
- Login Servcie 메서드 예외처리 및 예외메시지 추가/수정
=> refactor: login 

src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceImpl.java
ex) #이슈번호
닉네임 변경 분기 처리 오류 수정
닉네임 변경 시 스티비 서비스 비활성화 (제대로 동작하는지 확인 필요)
=> fix: MemberInfoServiceImpl.java

src/main/java/com/be3c/sysmetic/domain/member/dto/MemberPatchInfoRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/MemberPutPasswordRequestDto.java
#172 
json property 카멜 케이스로 변경
=> fix: user info modify bug #172

src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyStatisticsServiceImpl.java
user 권한 검증시 strategy id로 비교하던 로직 변경
#181 
strategy의 trader id로 검증하도록 수정
=> fix: user 권한 검증 로직 수정

src/main/java/com/be3c/sysmetic/domain/member/controller/InterestStrategyController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/InterestStrategyControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/member/dto/FollowDeleteRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/FollowPutRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/InterestStrategyGetRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/service/InterestStrategyService.java, src/main/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/ReplyServiceImpl.java
#178
완료
- 관심 전략 추가
- 관심 전략 단일 삭제 / 선택 삭제 분리
- 관심 전략 등록 시 이메일 발송 에러로 인한 주석 처리 (평일 중 수정)
=> fix: 전략 관심등록 삭제 수정

src/main/java/com/be3c/sysmetic/domain/member/controller/MemberInfoController.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceImpl.java
=> fix: 프로필 이미지 변경 확인

src/main/java/com/be3c/sysmetic/domain/member/controller/InquiryController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/InquiryControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeContoller.java, src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/member/dto/NoticeModifyRequestDto.java, src/main/resources/application.properties, src/test/java/com/be3c/sysmetic/domain/member/service/NoticeServiceTest.java
문의에서 로그인한 회원의 아이디 하드코딩 수정
#176
문의에서 로그인한 회원의 아이디 하드코딩 수정
inquiry 엔티티 수정
기타 수정
=> Fix: 문의에서 로그인한 회원의 아이디 하드코딩 수정 #176

src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/AccountImageRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/exception/StrategyExceptionMessage.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/MonthlyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageServiceImpl.java
실계좌이미지 관련 이슈 해결
#184 
실계좌이미지 검증 로직 수정
파일과 dto 분리
일간분석 데이터 최신순 정렬
월간분석 데이터 최신순 정렬
=> fix: 실계좌이미지 관련 이슈 해결

src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageServiceImpl.java
전략 상태 검증 로직 수정
#192 
전략 상태 검증 로직 수정
=> fix: 전략 상태 검증 로직 수정

src/main/resources/application.properties
application.properties 수정
#200
application.properties 수정
=> settings: application.properties 수정 #200

src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/AccountImageDeleteRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageServiceImpl.java
실계좌이미지 다중 선택 삭제 기능 추가
#197 
실계좌 이미지 1개 삭제 API -> N개 삭제 API 변경
List를 받기 위한 request dto 추가
=> update: 실계좌이미지 다중 선택 삭제 기능 추가

src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/LogoutController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/MemberManagementController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/MemberGetResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/MemberManagementPatchRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/ResetPasswordRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/entity/MemberRole.java, src/main/java/com/be3c/sysmetic/domain/member/entity/MemberSearchType.java, src/main/java/com/be3c/sysmetic/domain/member/exception/MemberExceptionMessage.java, src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java, src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoService.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImpl.java, src/main/java/com/be3c/sysmetic/global/config/WebConfig.java, src/main/java/com/be3c/sysmetic/global/config/security/SecurityConfig.java, src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/controller/MemberManagementControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceImplTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImplTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceTest.java
관리자 회원 관리 - 쿼리문 및 일부 로직 수정, 예외처리 추가
#183
- 회원 조회 쿼리문 수정
- 회원 등급변경 서비스 로직 수정
- 회원 강제탈퇴 메서드 추가
- Security CORS 설정을 클래스(WebConfig)에서 SecurityConfig 내부 설정으로 변경
=> refactor: 회원 관리 리팩토링

src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StockListDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDetailDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyListByTraderDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyListDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/TraderStrategyListDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyListRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyStatisticsServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/util/StockGetter.java, src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyViewAuthorize.java, src/main/java/com/be3c/sysmetic/global/util/file/service/FileServiceImpl.java
전략 api 통합
#186
- api 통합 완료
- if문 분기 설정
=> update: 전략 api 통합 #186

src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImpl.java, src/test/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceTest.java
=> Bugfix: compile error fix

src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImpl.java
=> fix: save 메서드 추가

src/main/java/com/be3c/sysmetic/domain/member/controller/InquiryController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/InquiryControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeContoller.java
Refactor: notice inquiry endpoint #212
#212
문의와 공지사항 엔드포인트 수정
=> Refactor: notice inquiry endpoint #212

src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategySearchRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
**전략 상세 조건 검색**
#196 
전략 상세 조건 검색에서 "운용 기간" 조건 추가
=> update : 전략 상세 조건 검색 - 운용 기간 추가 #196

src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java
누적데이터가 null일 경우 처리
#216 
null일 경우 0.0으로 처리
=> fix: 조회 data가 null일 경우 처리

src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockServiceImpl.java
ex) #이슈번호
인터페이스와 impl 컨트롤러 동기화
=> Fix: 종목 / 매매유형 수정

src/main/java/com/be3c/sysmetic/global/util/admin/controller/AdminMainController.java, src/main/java/com/be3c/sysmetic/global/util/admin/dto/AdminInquiryResponseDto.java, src/main/java/com/be3c/sysmetic/global/util/admin/dto/AdminMainResponseDto.java, src/main/java/com/be3c/sysmetic/global/util/admin/dto/AdminNoticeResponseDto.java, src/main/java/com/be3c/sysmetic/global/util/admin/dto/MemberCountResponseDto.java, src/main/java/com/be3c/sysmetic/global/util/admin/dto/RunReportResponseDto.java, src/main/java/com/be3c/sysmetic/global/util/admin/dto/StrategyCountResponseDto.java
=> feature: 관리자 메인 페이지

src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDetailDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
**methodId 추가**
#220 
전략 상세 페이지 응답 DTO `methodId` 추가
=> 전략 상세 - methodId 추가 #220

src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/FindEmailRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/LoginRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/ResetPasswordRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/exception/MemberExceptionMessage.java, src/main/java/com/be3c/sysmetic/domain/member/exception/handler/MemberExceptionHandler.java, src/main/java/com/be3c/sysmetic/domain/member/service/AccountService.java, src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java, src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java, src/main/java/com/be3c/sysmetic/global/config/security/RedisUtils.java, src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/controller/MemberManagementControllerTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImplTest.java
이메일 찾기 및 비밀번호 재설정 리팩토링
#206
- AccountController 및 Service 반환값 및 예외처리 리팩토링
- valid message를 error.properties 메시지를 사용하도록 수정
- valid 관련 ExceptionHandler 메시지 전달 부분 수정
- MemberExceptionMessage 에러 메시지 일부 수정
- Token 처리 과정 주석 수정
=> refactor: 이메일 찾기 및 비밀번호 재설정 리팩토링

src/main/java/com/be3c/sysmetic/domain/strategy/controller/ExcelControllerImpl.java
**[Swagger에서 multipart/form-data 인식 문제 해결]**
#111
- Swagger에서 multipart/form-data를 자동으로 인식하지 못하는 문제를 해결하기 위해 @PostMapping에 consumes 속성을 명시하여 파일 업로드를 올바르게 처리하도록 수정
=> fix: Swagger에서 multipart/form-data 인식 문제 해결 #111

src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java, src/main/java/com/be3c/sysmetic/domain/member/dto/TokenApiResponseDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockController.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AdminStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/ReplyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyAllowApprovalServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/global/config/security/JwtAuthenticationFilter.java
=> fix: 1차 수정 완성

src/main/java/com/be3c/sysmetic/domain/strategy/controller/ExcelController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/ExcelControllerImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/ExcelServiceImpl.java
**[한글 깨짐 문제 해결]**
#111
- 한글이 깨져서 파일을 불러오지 못하는 문제 해결
=> fix: 한글 깨짐 문제 해결 #111

src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyGraphAnalysis.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyIndicatorsCalculator.java
**전략 상세 페이지 그래프 재반영**
#153 
전략 상세 페이지 내 그래프 코드 재반영
=> 전략 상세 페이지 그래프 재반영 #153

src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyIndicatorsCalculator.java
**현재자본인하율 추가**
#203
`현재자본인하율 currentCapitalReductionRate` 응답에 추가
=> Update : currentCapitalReductionRate 응답에 추가 #203

src/main/java/com/be3c/sysmetic/domain/strategy/service/ExcelServiceImpl.java
**[엑셀 업로드 시 내결함성 강화]**
#111
엑셀 업로드 시 빈 셀이 발생해도 에러가 나지 않도록 수정
=> refactor: 엑셀 업로드 시 내결함성 강화 #111

src/main/java/com/be3c/sysmetic/domain/member/entity/InterestStrategy.java, src/main/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodController.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyApprovalRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyDetailRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AdminStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyAllowApprovalServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyServiceImpl.java
=> fix: 2차 수정

src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyAllowApprovalServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyServiceImpl.java
=> Fix: second final fix #240

src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
**대표전략 분석 지표**
#203 
대표전략 분석 지표 기능 개발
=> update : 대표전략 분석 지표 기능 개발 #203

src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageControllerDocs.java
=> update : 엔드 포인트 추가 #203

src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java
=> :startdate 수정 #203

src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDeleteRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyStatisticsGetResponseDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStatistics.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/MonthlyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyStatisticsServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyViewAuthorize.java, src/test/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImplTest.java
전략 탭 조회 검증 로직 변경
월간분석 조회 api 변경
전략 다중 삭제 반영
관리자 전략 삭제 가능하도록 변경 
#239 
- 전략 탭 조회 검증 로직 변경
- 월간분석 조회 api 변경
- 전략 다중 삭제 반영
- 관리자 전략 삭제 가능하도록 변경
=> bugfix: find strategy error #239

src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
전략 조회 상태 변경
#249 
일간분석 등록 후 분석 지표 그래프 테이블 생성시 전략 상태에 따른 조회 로직 변경
=> bugfix: 전략 조회 상태 변경

src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDetailDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java, src/main/java/com/be3c/sysmetic/global/util/file/service/FileService.java, src/main/java/com/be3c/sysmetic/global/util/file/service/FileServiceImpl.java
**[파일 수정 로직 개선 및 전략 상세보기 PDF 조회 기능 추가]**
#111
- 파일 수정 로직 수정
- 전략 상세보기에서 PDF 조회 기능 추가
=> feat: 파일 수정 로직 개선 및 전략 상세보기 PDF 조회 기능 추가 #111

src/main/java/com/be3c/sysmetic/domain/strategy/dto/RejectStrategyApprovalDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyApprovalRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AdminStrategyServiceImpl.java
=> fix: 3차 수정

src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
#253
- 월간분석 조회 API 수정
- 일간분석 삭제 로직 수정
- 일간분석 수정시 그래프 테이블 수정 로직 수정
=> bugfix: find monthly issue #253

src/main/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/AllowApprovalRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyStatusCode.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AdminStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyAllowApprovalServiceImpl.java
ex) #이슈번호
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
=> fix: 4차 수정

src/main/java/com/be3c/sysmetic/domain/strategy/dto/RejectStrategyApprovalDto.java
ex) #이슈번호
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
=> Fix/fourth fix final #240

src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyServiceImpl.java
월간분석 조회 로직 수정
#261 
null 체크, empty 체크 순서 변경
=> fix: 월간분석 조회 로직 수정

src/main/java/com/be3c/sysmetic/domain/member/repository/InterestStrategyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/AdminStrategyAllowController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListController.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/AdminStrategyGetResponseDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyAlgorithmResponseDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDetailDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyListDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategySearchResponseDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/TraderStrategyListDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyApprovalRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AdminStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategySearchServiceImpl.java
ex) #이슈번호
if문 분기 설정
전략 목록에서 아이콘 패스 추가
=> Fix: fifth fix final #240

src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/SmScoreTopFive.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/TraderRankingDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/MainPageRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
**메인 페이지 트레이더 이미지 추가**
#255 
메인 페이지 트레이더 이미지 추가, 서비스 코드 리팩토링
=> Refactor : 메인 페이지 트레이더 이미지 추가 #255

src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImpl.java
제안서 삭제 로직 수정
#269 
전략 등록
- 요청 파일 존재할 경우 -> 파일 업로드
전략 수정
- 요청 파일 존재할 경우 -> 기존 파일이 있다면 파일 업데이트, 기존 파일이 없다면 파일 업로드
- 요청 파일 존재하지 않을 경우 -> 기존 파일이 있다면 삭제 처리
=> refactor: 제안서 삭제 로직 수정

src/main/java/com/be3c/sysmetic/domain/member/controller/InquiryController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeContoller.java, src/main/java/com/be3c/sysmetic/domain/member/repository/InquiryRepository.java, src/main/java/com/be3c/sysmetic/domain/member/repository/NoticeRepository.java, src/main/java/com/be3c/sysmetic/domain/member/service/InquiryAnswerService.java, src/main/java/com/be3c/sysmetic/domain/member/service/InquiryAnswerServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/InquiryService.java, src/main/java/com/be3c/sysmetic/domain/member/service/InquiryServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/NoticeService.java, src/main/java/com/be3c/sysmetic/domain/member/service/NoticeServiceImpl.java
InquiryService에서 getFilePath 사용 시 파일이 없으면 에러가 발생한다.
#275
InquiryService에서 getFilePath 사용 시 없으면 null 값이 필요하나 파일이 없으면 에러가 발생한다.
InquiryService에서 getFilePathNullable로 수정
=> Fix: InquiryService에서 getFilePathNullable로 수정 #275

src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyStatusCode.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyApprovalRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/AdminStrategyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/ReplyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/util/ApprovalStatus.java
#266 
- 관리자 페이지 승인 요청 상태 반환값 한글로 통일
- 전략 상세 페이지 접근 가능 여부 확인 추가
=> Refactor: approval status fix #266

src/main/java/com/be3c/sysmetic/domain/strategy/controller/ExcelController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/ExcelControllerImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/ExcelServiceImpl.java
**[엑셀 오류 해결]**
#111
- 엑셀 업로드 시 발생한 파일 처리 오류 해결
- 엑셀 다운로드 시 파일 포맷 및 응답 처리 오류 해결
=> fix: 엑셀 오류 해결 #111

src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
**메인 페이지 분석 그래프 데이터 전체 전송**
#255 
메인 페이지 분석 그래프 데이터 기간 선택 없이 전체 전송
=> Refactor : 메인 페이지 분석 그래프 - 기간 선택 제거 #255

src/main/java/com/be3c/sysmetic/domain/strategy/dto/MainPageAnalysisDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
=> 메인 페이지 x축 두 번 보내기 #255

src/main/java/com/be3c/sysmetic/domain/member/service/InquiryServiceImpl.java
문의 서비스 traderProfileImagePath을 getFilePath로 수정
#283
문의 서비스 traderProfileImagePath을 getFilePathNullable -> getFilePath로 수정
=> Fix: 문의 서비스 traderProfileImagePath을 getFilePath로 수정 #283

src/main/java/com/be3c/sysmetic/domain/strategy/dto/PageReplyResponseDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/ReplyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/ReplyServiceImpl.java
- 댓글 전송 데이터 추가
#285 
완료
- 댓글 전송 데이터 추가
=> fix: 댓글 전송 데이터 추가

src/main/java/com/be3c/sysmetic/domain/strategy/dto/MonthlyForRepo.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDetailDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/YearlyRecord.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/MonthlyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
**전략 상세 페이지 월간 손익률 차트 수정**
#255 
전략 상세 페이지 월간 손익률 차트 수정
=> Refactor : 전략 상세 페이지 월간 손익률 차트 수정 #255

src/main/java/com/be3c/sysmetic/domain/member/controller/InquiryController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeContoller.java, src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/member/repository/InquiryRepository.java, src/main/java/com/be3c/sysmetic/domain/member/repository/NoticeRepository.java, src/main/java/com/be3c/sysmetic/domain/member/repository/NoticeRepositoryImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/InquiryServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/NoticeServiceImpl.java, src/main/resources/application.properties, src/test/java/com/be3c/sysmetic/domain/member/service/InquiryServiceTest.java, src/test/java/com/be3c/sysmetic/domain/member/service/NoticeServiceTest.java
일반 공지사항 비공개 글 보이는 것 수정, 공지사항, 문의 테스트 수정
#289
일반 공지사항 목록, 상세 페이지에서 비공개 글 보이는 것 수정
공지사항, 문의 테스트 수정
securityUtils.getUserIdInSecurityContext() 사용 부분 주석처리
StrategyBadRequestException 사용하던 것을 삭제하고 repository에 조건 추가한 메소드 만드는 것으로 수정
=> Update: 일반 공지사항 비공개 글 보이는 것 수정, 공지사항, 문의 테스트 수정 #289

src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/MethodDeleteRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/ReplyDeleteRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/dto/StockDeleteRequestDto.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/ReplyServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockService.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StockServiceImpl.java
종목, 매매 유형 선택 삭제
- 종목, 매매유형 선택 삭제
=> fix: 종목, 매매유형 선택삭제

src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchController.java, src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategySearchServiceImpl.java
**전략 목록 알고리즘별 검색 - DEFENSIVE 방어형**
#255 
전략 목록 알고리즘별 검색 - DEFENSIVE 방어형 기능 구현
=> 전략 목록 알고리즘별 검색 - DEFENSIVE 방어형 #255

src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
**전략 목록 알고리즘별 검색 DEFENSIVE 정렬 수정**
#255 
전략 목록 알고리즘별 검색 DEFENSIVE 방어형 정렬 수정
=> 전략 목록 알고리즘별 검색 DEFENSIVE 방어형 순위 수정 #255

src/main/java/com/be3c/sysmetic/domain/member/controller/InquiryController.java, src/main/java/com/be3c/sysmetic/domain/member/controller/InquiryControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeContoller.java, src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeControllerDocs.java, src/main/java/com/be3c/sysmetic/domain/member/dto/InquiryAnswerAdminShowResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/InquiryAnswerInquirerShowResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/InquiryAnswerTraderShowResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/InquiryModifyPageShowResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/NoticeDetailAdminShowResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/NoticeDetailShowResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/NoticeModifyRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/NoticeSaveRequestDto.java, src/main/java/com/be3c/sysmetic/domain/member/dto/NoticeShowModifyPageResponseDto.java, src/main/java/com/be3c/sysmetic/domain/member/entity/Notice.java, src/main/java/com/be3c/sysmetic/domain/member/repository/InquiryAnswerRepository.java, src/main/java/com/be3c/sysmetic/domain/member/service/InquiryService.java, src/main/java/com/be3c/sysmetic/domain/member/service/InquiryServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/member/service/NoticeService.java, src/main/java/com/be3c/sysmetic/domain/member/service/NoticeServiceImpl.java, src/test/java/com/be3c/sysmetic/domain/member/service/NoticeServiceTest.java
fix: 공지사항 수정 API exists 반영 안 됨 수정
#297
공지사항 수정 API exists 변경 반영 안 됨 수정
=> Fix: 공지사항 수정 API exists 반영 안 됨 수정 #297

src/main/java/com/be3c/sysmetic/global/config/AuditorAwareImpl.java
**[Audit 설정을 Security 설정에 맞게 변경]**
#32
- Security 설정 적용으로 Audit 기능 정상화
=> refactor: Audit 설정을 Security 설정에 맞게 변경 #32

src/main/java/com/be3c/sysmetic/domain/strategy/service/ExcelServiceImpl.java
**엑셀 파일 업로드 시 그래프 레포지토리에 데이터 저장**
#255 
엑셀 파일 업로드 시 그래프 레포지토리에 데이터 저장
=> 엑셀 파일 업로드 시 그래프 레포지토리에 데이터 저장 #255

src/main/java/com/be3c/sysmetic/domain/member/repository/InquiryAnswerRepository.java, src/main/java/com/be3c/sysmetic/domain/member/repository/InquiryRepository.java, src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceImpl.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStockReferenceRepository.java
=> fix: 회원 탈퇴 수정 #305

src/main/java/com/be3c/sysmetic/domain/member/controller/NoticeContoller.java, src/main/java/com/be3c/sysmetic/domain/member/dto/NoticeModifyRequestDto.java
DTO deleteFileIdList 오타 수정
#308
DTO deleteFileIdList 오타 수정
=> Fix: DTO deleteFileIdList 오타 수정 #308

src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java
tokenProvider의 generateToken() 메서드 로직 일부 수정
#307
- (기존) "RC"로 시작하는 roleCode만 role로 변경
- (변경) 모든 roleCode를 role로 변경하도록 수정
=> update: tokenProvider 수정

src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java, src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
**전략 상세 분석 지수 업데이트**
#255 
전략 상세 분석 지수 업데이트
=> 전략 상세 분석 지수 업데이트 #255
